import {beforeAll,describe,it,expect} from 'vitest';
import {generateBlueprint as generateBaselineBlueprint,generateBlueprintV18,DEFAULT_ORDER} from '../src/generation/generate';
// Preserve the complete V1.8.4.1 regression contract; new requirements are tested separately.
const generateBlueprint=(...args:Parameters<typeof generateBaselineBlueprint>)=>generateBaselineBlueprint(args[0],args[1],{...args[2],version:args[2]?.version??'1.8.4.1'});
import {createDesignDoctrine,DOCTRINES,validateDesignDoctrine,plus,emptyResources,weaponResources,prepareIntegratedArmament} from '../src/generation/production/doctrine';
import {mountStandard} from '../src/generation/weapons/standards';
import type {ShipBlueprint} from '../src/blueprint/types';
let b:ShipBlueprint;
beforeAll(()=>{b=generateBlueprint(DEFAULT_ORDER,7,{architecture:'MONOLITHIC',family:'WEDGE_CITADEL'});},120000);
describe('finite order-driven design doctrine',()=>{
 it('normalizes competing all-high demands rather than multiplying physical capacity',()=>{const q=structuredClone(b),normal=createDesignDoctrine(q);q.order.priorities=Object.fromEntries(Object.keys(q.order.priorities).map(k=>[k,100])) as typeof q.order.priorities;const high=createDesignDoctrine(q);expect(high.total).toEqual(normal.total);const allocated=Object.values(high.allocations).reduce(plus,emptyResources());expect(allocated.massTonnes).toBeCloseTo(high.total.massTonnes,5);expect(allocated.volumeM3).toBeCloseTo(high.total.volumeM3,5);expect(high.adjustments.some(a=>a.groupId==='resources')).toBe(true);});
 it('gives mass classes distinct finite capacity at identical hull geometry',()=>{const q=structuredClone(b),values=['Light','Standard','Heavy','Superheavy'].map(massClass=>{q.order.massClass=massClass as typeof q.order.massClass;return createDesignDoctrine(q);});expect(values.map(d=>d.total.massTonnes)).toEqual([...values.map(d=>d.total.massTonnes)].sort((a,c)=>a-c));expect(new Set(values.map(d=>d.total.massTonnes)).size).toBe(4);expect(new Set(values.map(d=>d.total.volumeM3)).size).toBe(1);});
 it('uses explicit mission and calibre policies beyond a budget multiplier',()=>{expect(DOCTRINES['Missile Ship'].shares.MISSILE).toBeGreaterThan(DOCTRINES.Battleship.shares.MISSILE);expect(DOCTRINES['Patrol Ship'].large).toBe('forbidden');expect(DOCTRINES.Battlecruiser.mobility).toBeGreaterThan(DOCTRINES.Battleship.mobility);expect(new Set(Object.values(DOCTRINES).map(d=>JSON.stringify(d))).size).toBe(9);});
 it('charges installed authoritative mounts and catches corrupted budgets or records',()=>{expect(validateDesignDoctrine(b)).toEqual([]);for(const mutate of [(q:ShipBlueprint)=>q.designDoctrine!.usage.weapons.massTonnes=0,(q:ShipBlueprint)=>q.designDoctrine!.remaining.volumeM3=999,(q:ShipBlueprint)=>q.designDoctrine!.actual=[],(q:ShipBlueprint)=>q.designDoctrine!.equipmentTargets[0].installed=999,(q:ShipBlueprint)=>q.designDoctrine!.equipment[0].resources.volumeM3=0]){const q=structuredClone(b);mutate(q);expect(validateDesignDoctrine(q).length).toBeGreaterThan(0);}});
 it('identifies one selected audited candidate for each installed whole group',()=>{const w=b.weaponLayout!,selected=w.attempts.filter(a=>a.selected);expect(new Set(selected.map(a=>a.groupId)).size).toBe(selected.length);expect(selected.map(a=>a.groupId).sort()).toEqual([...new Set(w.mounts.map(m=>m.groupId))].sort());for(const a of selected)expect(a.variant).toEqual(w.groups.find(g=>g.id===a.groupId));});
 it('retains unchanged L/XL standards when evaluating costs and rejecting an undersized axial host',()=>{const before=mountStandard('XL',40);weaponResources('XL','SPINAL',40);expect(mountStandard('XL',40)).toEqual(before);const q=generateBlueprintV18({...DEFAULT_ORDER,role:'Spinal Gun Ship',length:40},11,{productionBase:true} as any);q.designDoctrine=createDesignDoctrine(q);prepareIntegratedArmament(q);expect(q.hardpoints.some(h=>h.type==='Spinal')).toBe(false);expect(q.designDoctrine.adjustments.some(a=>a.reason.startsWith('XL omitted'))).toBe(true);});
 it('accepts full-size XL only when a real rectangular axial host and finite allocation contain it',()=>{
  const q=structuredClone(b),standard=mountStandard('XL',300),host=q.structuralVolumes[0],width=standard.envelope.width*2,height=standard.envelope.height*2,length=standard.envelope.length*2;
  q.role=q.order.role='Spinal Gun Ship';host.dimensions={x:width,y:height,z:length};host.position={x:0,y:0,z:0};host.geometry.stations=[-length/2,length/2].map(z=>({...host.geometry.stations[0],z,width,height,profile:'box' as const,sectionRing:undefined,topSlope:0,bottomSlope:0,sideSlope:0,bevel:0}));
  q.hardpoints=[{id:'full-size-xl',type:'Spinal',size:'XL',parentId:host.id,position:{x:0,y:0,z:-length/2},normal:{x:0,y:0,z:-1},radius:standard.footprint.width/2,allowedCategories:['SPINAL']}];
  q.designDoctrine=createDesignDoctrine(q);prepareIntegratedArmament(q);expect(q.hardpoints).toHaveLength(1);expect(q.hardpoints[0].size).toBe('XL');expect(mountStandard('XL',300)).toEqual(standard);
 });
 it('keeps historical blueprints without doctrine loadable and unmodified',()=>{const q=generateBlueprintV18(DEFAULT_ORDER,7);const before=JSON.stringify(q);expect(q.designDoctrine).toBeUndefined();expect(validateDesignDoctrine(q)).toEqual([]);expect(JSON.stringify(q)).toBe(before);});
});
