import {chromium} from 'playwright-core';import {readFileSync,writeFileSync} from 'node:fs';import assert from 'node:assert/strict';
const browser=await chromium.launch({executablePath:'/usr/bin/chromium',headless:true,args:['--no-sandbox','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});const page=await browser.newPage({viewport:{width:1440,height:1050}});const checks=[],errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});const check=(name,ok)=>{assert(ok,name);checks.push({name,passed:true});console.log(name);};const manifest=()=>page.locator('#json-content').textContent().then(JSON.parse);
try{
 await page.goto('http://localhost:4282');await page.waitForFunction(()=>document.querySelector('#json-content')?.textContent.length>100,null,{timeout:90000});check('Production build without QA hooks',await page.evaluate(()=>!window.shipyardQA));
 await page.locator('#import-file').setInputFiles('qa/v1.8.5.4.2/470-baseline.json');await page.waitForFunction(()=>document.querySelector('#hardpoint-summary')?.textContent.includes('120'),null,{timeout:90000});const saved=JSON.stringify(await manifest());
 await page.locator('#hardpoint-inspector details').first().evaluate(e=>e.open=true);await page.locator('#equipment-preview').evaluate(e=>e.open=true);
 await page.locator('#hardpoint-selection').selectOption('slot-54');await page.locator('#equipment-scope').selectOption('BATTERY');await page.locator('#equipment-refine').check();await page.locator('#equipment-preview-on').check();await page.waitForFunction(()=>document.querySelector('#equipment-results').textContent.includes('Temporary fitment'),null,{timeout:90000});
 check('Worker fits refined six-slot paired battery', (await page.locator('#equipment-results').textContent()).includes('PARTIAL_ARC')&&(await page.locator('#equipment-results').textContent()).includes('3 measured M slots per side'));
 check('Preview leaves canonical Blueprint unchanged',JSON.stringify(await manifest())===saved);
 await page.locator('#equipment-arcs').check();await page.waitForFunction(()=>document.querySelector('#equipment-results').textContent.includes('cached'),null,{timeout:90000});check('Repeated fit uses cache and arc display',true);
 await page.locator('#equipment-results').evaluate(el=>el.style.maxHeight='280px');await page.screenshot({path:'qa/v1.8.5.4.2/ui-preview.jpg',type:'jpeg',quality:85,fullPage:true});
 await page.locator('#equipment-preview-on').uncheck();check('OFF restores original canonical state',JSON.stringify(await manifest())===saved&&(await page.locator('#equipment-results').textContent()).includes('restored'));
 await page.locator('#equipment-scope').selectOption('SINGLE');await page.locator('#hardpoint-selection').selectOption('slot-27');await page.locator('#equipment-module').selectOption('gun-406');await page.locator('#equipment-preview-on').check();await page.waitForFunction(()=>document.querySelector('#equipment-results').textContent.includes('INCOMPATIBLE'),null,{timeout:90000});check('Oversized module failure exposed',true);
 await page.locator('#equipment-preview-on').uncheck();
 await page.locator('#equipment-scope').selectOption('AUTO');await page.locator('#equipment-preview-on').check();await page.waitForFunction(()=>document.querySelector('#equipment-results').textContent.includes('omitted by preview cap'),null,{timeout:90000});
 check('Representative AUTO limit and untested omissions exposed',(await page.locator('#equipment-results').textContent()).includes('67 omitted'));
 await page.locator('#equipment-preview-on').uncheck({force:true});check('AUTO OFF preserves original JSON',JSON.stringify(await manifest())===saved);
 await page.locator('#reload').click({force:true});check('Stored reload restores Preview OFF',!(await page.locator('#equipment-preview-on').isChecked()));check('Reload canonical JSON preserved',JSON.stringify(await manifest())===saved);
 const download=page.waitForEvent('download');await page.locator('#export').click({force:true});await(await download).saveAs('qa/v1.8.5.4.2/export.json');check('Export contains no temporary equipment',JSON.stringify(JSON.parse(readFileSync('qa/v1.8.5.4.2/export.json','utf8')))===saved);
 check('Console errors zero',errors.length===0);writeFileSync('qa/v1.8.5.4.2/ui-report.json',JSON.stringify({checks,errors},null,2));console.log(checks.length,'UI checks passed');
}finally{await browser.close();}
