import {renderSession,png} from './helpers/render-session.mjs';
import {mkdir,writeFile} from 'node:fs/promises';import assert from 'node:assert/strict';
const out=process.env.OUT||'qa/v1.8.5.3.1/render';await mkdir(out,{recursive:true});const {browser,page,errors}=await renderSession();
try{const result=await page.evaluate(async()=>{
 const {generateBlueprint,DEFAULT_ORDER}=await import('/src/generation/generate.ts'),{addMesoStructures}=await import('/src/generation/meso/build.ts'),{addMesoStructures:legacy}=await import('/src/generation/meso/legacy-build.ts'),{validateBlueprint}=await import('/src/validation/validate.ts'),{ArmorQARenderer}=await import('/src/rendering/armor-qa.ts');
 const rows=[],captures=[],examples=[],r=new ArmorQARenderer(800);
 const capture=(b,view,center,extent,detailMode='HIGH')=>r.capture(b,'COMPLETE',view,{reviewLighting:true,underbodyLighting:view==='BOTTOM'||view==='LOW-ISOMETRIC',scale:'fixed',detailMode,closeup:{center,extent}});
 for(const shipyardId of ['vesper','forge','serein'])for(const length of [120,300,600])for(const seed of [0,13]){
  const order={...structuredClone(DEFAULT_ORDER),shipyardId,length,role:'Patrol Ship',priorities:{firepower:10,survivability:30,mobility:85,endurance:40,missile:10,sensor:40}},opts={architecture:'CORE_AND_NACELLES',family:'ENGINE_DOMINANT'},before=generateBlueprint(order,seed,{...opts,version:'1.8.5.3'}),b=generateBlueprint(order,seed,opts);
  const base=generateBlueprint(order,seed,{...opts,version:'1.8.5'}),isolated=structuredClone(base);legacy(base,{kinds:['ENGINE_ROOT_TRANSITION']});addMesoStructures(isolated,{kinds:['ENGINE_ROOT_TRANSITION']});
  const q=structuredClone(b);q.mesoStructurePlan=before.mesoStructurePlan;q.generatorVersion=before.generatorVersion;q.materialAppearance=before.materialAppearance;if(JSON.stringify(q)!==JSON.stringify(before))throw Error('Canonical physical regression');
  const issues=validateBlueprint(b);if(issues.length)throw Error(issues.join('; '));if(JSON.stringify(generateBlueprint(order,seed,opts))!==JSON.stringify(b))throw Error('JSON determinism');
  const roots=b.mesoStructurePlan.placements.filter(p=>p.kind==='ENGINE_ROOT_TRANSITION'),rootZones=b.mesoStructurePlan.detectedZones.filter(z=>z.root),decisions=b.mesoStructurePlan.decisions.filter(d=>rootZones.some(z=>z.id===d.zoneId)),reasonCounts={};for(const d of decisions)if(d.status==='omitted')reasonCounts[d.category]=(reasonCounts[d.category]||0)+1;
  rows.push({shipyardId,length,seed,engineSummary:b.engines.map(e=>({id:e.id,parent:e.parentId,position:e.position,direction:e.direction,nozzleRadius:e.nozzleRadius,nozzleLength:e.nozzleLength,acceptedRoots:roots.filter(p=>p.parentEquipmentId===e.id).length,detectedZones:rootZones.filter(z=>z.equipmentId===e.id).length})),beforeRoots:before.mesoStructurePlan.placements.filter(p=>p.kind==='ENGINE_ROOT_TRANSITION').length,legacyRootOnly:base.mesoStructurePlan.placements.length,newRootOnly:isolated.mesoStructurePlan.placements.length,roots:roots.map(p=>({id:p.id,parent:p.parentStructureId,engine:p.parentEquipmentId,variant:p.parameters.rootVariant,size:p.parameters,contacts:p.attachment.contacts.length,position:p.attachment.position})),zoneCount:rootZones.length,finalAcceptedZones:rootZones.filter(z=>z.finalStatus==='accepted').length,candidateOmissions:reasonCounts,finalZoneOmissions:rootZones.filter(z=>z.finalStatus==='omitted').reduce((a,z)=>(a[z.omissionCategory]=(a[z.omissionCategory]||0)+1,a),{}),issues});
  if(roots.length&&!examples.some(e=>e.shipyardId===shipyardId)){const root=roots[0],engine=b.engines.find(e=>e.id===root.parentEquipmentId),center=engine.position,extent=Math.max(engine.nozzleRadius*9,35);examples.push({shipyardId,b,center,extent});for(const view of ['AFT','LEFT','ISOMETRIC','LOW-ISOMETRIC'])for(const [stage,bp]of [['before',before],['after',b]])captures.push({name:`${shipyardId}-${stage}-${view}`,...capture(bp,view,center,extent)});captures.push({name:`${shipyardId}-detail-OFF`,...capture(b,'ISOMETRIC',center,extent,'OFF')});for(const [stage,bp]of [['before',before],['after',b]])captures.push({name:`${shipyardId}-whole-${stage}`,...capture(bp,'ISOMETRIC',{x:0,y:0,z:0},length*1.25)});const reload=capture(JSON.parse(JSON.stringify(b)),'ISOMETRIC',center,extent),original=capture(b,'ISOMETRIC',center,extent);if(reload.pixels!==original.pixels)throw Error('Reload pixels');}
  await new Promise(resolve=>setTimeout(resolve,0));
 }
 const sparse=[];
 for(const [architecture,family]of [['TRUSS_POD','SPLIT_FRAME'],['HYBRID','SPLIT_FRAME'],['SPINE_AND_MODULES','WEAPON_DOMINANT'],['CORE_AND_NACELLES','ENGINE_DOMINANT'],['TWIN_HULL','WIDE_CARRIER']]){
  const opts={architecture,family},before=generateBlueprint(DEFAULT_ORDER,7,{...opts,version:'1.8.5.3'}),b=generateBlueprint(DEFAULT_ORDER,7,opts),issues=validateBlueprint(b);if(issues.length)throw Error(issues.join('; '));const zones=b.mesoStructurePlan.detectedZones.filter(z=>z.connectorId),placements=b.mesoStructurePlan.placements.filter(p=>zones.some(z=>z.id===p.zoneId));sparse.push({architecture,family,before:before.mesoStructurePlan.placements.length,after:b.mesoStructurePlan.placements.length,junctionZones:zones.length,junctionPlacements:placements.map(p=>({kind:p.kind,parent:p.parentStructureId,size:p.parameters})),zoneDecisions:zones.map(z=>({id:z.id,status:z.finalStatus,reason:z.omissionCategory,candidates:z.candidateCount})),negativeSpaceUnchanged:JSON.stringify(b.macroDesign.negativeSpaceTargets)===JSON.stringify(before.macroDesign.negativeSpaceTargets)});for(const view of ['ISOMETRIC','BOTTOM'])for(const [stage,bp]of [['before',before],['after',b]])captures.push({name:`${architecture}-${stage}-${view}`,...capture(bp,view,{x:0,y:0,z:0},360)});
  await new Promise(resolve=>setTimeout(resolve,0));
 }
 const aegis=generateBlueprint(DEFAULT_ORDER,7),oldAegis=generateBlueprint(DEFAULT_ORDER,7,{version:'1.8.5.3'}),e=aegis.engines[0];examples.push({shipyardId:'aegis',b:aegis});for(const [stage,bp]of [['before',oldAegis],['after',aegis]])captures.push({name:`aegis-${stage}-AFT`,...capture(bp,'AFT',e.position,100)});
 r.dispose();return{rows,sparse,captures,examples};
});
 assert.deepEqual(errors,[]);for(const c of result.captures)await writeFile(`${out}/${c.name}.png`,png(c.pixels));for(const e of result.examples)await writeFile(`${out}/${e.shipyardId}.blueprint.json`,JSON.stringify(e.b));
 await writeFile(`${out}/report.json`,JSON.stringify({rows:result.rows,sparse:result.sparse,errors,captures:result.captures.map(({pixels,...c})=>c)},null,2));console.log(JSON.stringify({cases:result.rows.length,rootShips:result.rows.filter(r=>r.roots.length).length,rootPlacements:result.rows.reduce((s,r)=>s+r.roots.length,0),sparse:result.sparse.map(r=>({architecture:r.architecture,before:r.before,after:r.after,junctions:r.junctionPlacements.length})),errors}));
}finally{await browser.close();}
