import {beforeAll,it,expect} from 'vitest';
import * as THREE from 'three';
import {generateBlueprint,DEFAULT_ORDER} from '../src/generation/generate';
import {addMesoStructures} from '../src/generation/meso/build';
import {validateMesoStructures} from '../src/generation/meso/validate';
import {MESO_KINDS} from '../src/generation/meso/types';
import {mesoGeometry,mesoPerimeter} from '../src/generation/meso/geometry';
import {validateBlueprint} from '../src/validation/validate';
import {validateSurfaceReplay} from '../src/generation/appearance/validate';
import {createShip,disposeShip} from '../src/rendering/ship';
import {surfaceAssetStats} from '../src/rendering/surface-assets';
import {solidTriangles,area,cross} from '../src/generation/armor/panels';
import {dot,boundsOf} from '../src/generation/integration/contours';
import {rayBlocked} from '../src/generation/weapons/collision';
import {detailFrame} from '../src/generation/details/geometry';
import type {ShipBlueprint} from '../src/blueprint/types';
let old:ShipBlueprint,b:ShipBlueprint;
beforeAll(()=>{old=generateBlueprint(DEFAULT_ORDER,7,{version:'1.8.5.2'});b=generateBlueprint(DEFAULT_ORDER,7);},120000);
it('uses production V1.8.5.3 while preserving every prior physical and requirements field',()=>{expect(b.generatorVersion).toBe('1.8.5.3');const q=structuredClone(b);delete q.mesoStructurePlan;q.materialAppearance=old.materialAppearance;q.generatorVersion=old.generatorVersion;expect(q).toEqual(old);expect(validateBlueprint(b)).toEqual([]);});
it('preserves the explicit V1.8.5.2 generation contract and historical mesh replay',()=>{expect(generateBlueprint(DEFAULT_ORDER,7,{version:'1.8.5.2'})).toEqual(old);const root=createShip(old,'Normal');let meso=0;root.traverse(n=>{if(n.userData.mesoStructures)meso++;});expect(meso).toBe(0);disposeShip(root);},120000);
it('reproduces meso solids and final surface recipes under JSON reload and independent RNG',()=>{expect(JSON.parse(JSON.stringify(b))).toEqual(b);expect(generateBlueprint(DEFAULT_ORDER,7)).toEqual(b);expect(validateSurfaceReplay(b)).toEqual([]);},120000);
it('records real functional parents, thirteen support contacts, root station patches and omission causes',()=>{const p=b.mesoStructurePlan!;expect(p.namespace).toBe('meso-structure-v1');expect(p.placements.length).toBeGreaterThan(3);expect(new Set(p.placements.map(p=>p.kind)).size).toBeGreaterThanOrEqual(3);for(const a of p.placements){expect(a.attachment.contacts).toHaveLength(13);expect(a.attachment.rootPatch!.indices.length).toBeGreaterThan(3);expect(a.physicalOrVisualRole).toBe('VISUAL_STRUCTURE_ONLY');expect(a.combatProtection).toBe('NOT_SIMULATED');}expect(p.decisions.every(d=>d.reason)).toBe(true);expect(validateMesoStructures(b).issues).toEqual([]);});
it('constructs all eight parametric structures as closed positive finite solids',()=>{for(const kind of MESO_KINDS){const parts=mesoGeometry('test',kind,{width:12,length:30,height:3,taper:.8,clip:.18,style:'aegis'},{position:{x:0,y:0,z:0},frame:detailFrame({x:0,y:1,z:0}),contacts:[...mesoPerimeter(12,30,.18,.8),...Array.from({length:5},()=>({x:0,y:0,z:0}))].map(position=>({surfaceId:'parent',structureId:'hull',position,normal:{x:0,y:1,z:0}})),inset:.08,footprint:{width:12,length:30}});for(const p of parts){let volume=0;for(const t of solidTriangles(p.solid)){expect(area(t)).toBeGreaterThan(1e-7);volume+=dot(t[0],cross(t[1],t[2]))/6;}expect(volume).toBeGreaterThan(0);}}});
it('detects broken parents, detached station contacts, changed solid authority and false bounds',()=>{for(const f of[(q:ShipBlueprint)=>q.mesoStructurePlan!.placements[0].parentStructureId='missing',(q:ShipBlueprint)=>q.mesoStructurePlan!.placements[0].attachment.contacts[0].position.y+=9,(q:ShipBlueprint)=>q.mesoStructurePlan!.placements[0].parts[0].solid.vertices[0].x+=8,(q:ShipBlueprint)=>q.mesoStructurePlan!.bounds.max.y=-999]){const q=structuredClone(b);f(q);expect(validateMesoStructures(q).issues.length).toBeGreaterThan(0);}});
it('renders material batches and preserves meso in OFF without mutating the blueprint',()=>{const json=JSON.stringify(b),stats=surfaceAssetStats();for(const mode of ['Normal','Meso Structures','Without Meso']as const){const root=createShip(b,mode,'OFF');let pieces=0;root.traverse(n=>{if(n instanceof THREE.Mesh&&n.userData.functionalParts)pieces+=n.userData.functionalParts.filter((p:any)=>p.partId.startsWith('meso/')).length;});expect(pieces>0).toBe(mode!=='Without Meso');disposeShip(root);}expect(JSON.stringify(b)).toBe(json);expect(surfaceAssetStats().entries).toBe(stats.entries);});
it('never changes coverage or grants simulated protection when meso alone is generated',()=>{const q=structuredClone(old);addMesoStructures(q);expect(q.productionDesign).toEqual(old.productionDesign);expect(q.weaponLayout).toEqual(old.weaponLayout);expect(q.exteriorDetailPlan).toEqual(old.exteriorDetailPlan);expect(q.materialAppearance).toEqual(old.materialAppearance);});

it('detects a thin solid crossed between edge endpoints, supplementing sparse containment',()=>{const solid={vertices:[{x:0,y:-2,z:-2},{x:0,y:2,z:-2},{x:0,y:2,z:2},{x:0,y:-2,z:2}],indices:[0,1,2,0,2,3]};expect(rayBlocked({x:-10,y:0,z:0},{x:1,y:0,z:0},20,[{id:'thin-obstacle',solid,bounds:boundsOf(solid.vertices)}])).toBe('thin-obstacle');});
it('safely omits optional structures when all usable support is occupied without changing requirements',()=>{const q=structuredClone(old),physical=JSON.stringify(q.productionDesign),requirements=JSON.stringify(q.designRequirements);addMesoStructures(q,{kinds:[]});expect(q.mesoStructurePlan!.placements).toEqual([]);expect(q.mesoStructurePlan!.validation.issues).toEqual([]);expect(JSON.stringify(q.productionDesign)).toBe(physical);expect(JSON.stringify(q.designRequirements)).toBe(requirements);});

it('rejects a nonorthogonal attachment frame independently of part reconstruction',()=>{const q=structuredClone(b);q.mesoStructurePlan!.placements[0].attachment.frame.normal.x+=.3;expect(validateMesoStructures(q).issues.some(i=>i.includes('local frame'))).toBe(true);});

it('keeps functional structures in the actual source equipment/channel neighborhood',()=>{for(const p of b.mesoStructurePlan!.placements){if(p.kind==='WEAPON_BARBETTE_INTEGRATION'){const m=b.weaponLayout!.mounts.find(m=>m.equipment.prefabId===p.parentEquipmentId)!;expect(Math.abs(dot({x:p.attachment.position.x-m.position.x,y:p.attachment.position.y-m.position.y,z:p.attachment.position.z-m.position.z},m.frame.forward))).toBeLessThan(m.footprint.length*.5+.1);}if(p.kind==='MACHINERY_GALLERY'||p.kind==='SERVICE_RECESS_FRAME'){const c=b.productionDesign!.channels.find(c=>c.id===p.parentEquipmentId)!;expect(p.bounds.min.z).toBeGreaterThan(Math.min(...c.floor.map(p=>p.z))-3);expect(p.bounds.max.z).toBeLessThan(Math.max(...c.floor.map(p=>p.z))+3);}}});
