import {renderSession,png}from'./helpers/render-session.mjs';import{mkdir,writeFile}from'node:fs/promises';
const phase=process.env.PHASE||'b',out=process.env.OUT??`qa/v1.8.4/phase-${phase}`;await mkdir(out,{recursive:true});
const cases=phase==='b'?[7,11,23,41].map(seed=>({seed,architecture:'MONOLITHIC',family:'WEDGE_CITADEL'})):phase==='c'?[7,11,23].flatMap(seed=>[{seed,architecture:'BLOCK_ASSEMBLY',family:'HAMMERHEAD'},{seed,architecture:'CORE_AND_NACELLES',family:'ENGINE_DOMINANT'}]):phase==='d'?[7,11].flatMap(seed=>[{seed,architecture:'TRUSS_POD',family:'SPLIT_FRAME'},{seed,architecture:'TWIN_HULL',family:'WIDE_CARRIER'},{seed,architecture:'SPINE_AND_MODULES',family:'WEAPON_DOMINANT'}]):['aegis','vesper','forge','serein'].flatMap(shipyardId=>[40,120,300,600].map(length=>({seed:11,shipyardId,length,role:length<100?'Corvette':length>=500?'Battleship':'Cruiser'})));
const{browser,page,errors}=await renderSession();const rows=[];
try{for(const c of cases){const result=await page.evaluate(async(c)=>{
 const{generateBlueprint,DEFAULT_ORDER}=await import('/src/generation/generate.ts');const{validateBlueprint}=await import('/src/validation/validate.ts');const{ArmorQARenderer}=await import('/src/rendering/armor-qa.ts');const o={...structuredClone(DEFAULT_ORDER),shipyardId:c.shipyardId??'aegis',length:c.length??300,role:c.role??'Cruiser'},t=performance.now();
 try{const b=generateBlueprint(o,c.seed,{architecture:c.architecture,family:c.family}),ms=performance.now()-t,r=new ArmorQARenderer(640),shots=[];
 for(const view of['TOP','BOTTOM','LEFT','RIGHT','FRONT','AFT','ISOMETRIC','LOW-ISOMETRIC'])shots.push({view,shot:r.capture(b,'COMPLETE',view,{reviewLighting:true,underbodyLighting:view==='BOTTOM'||view==='LOW-ISOMETRIC',scale:'fit'})});r.dispose();
 return{ok:true,ms,family:b.macroDesign.family,architecture:b.architecture.grammar,armor:b.productionDesign.armor.length,finish:b.productionDesign.finish.length,coverage:b.productionDesign.coverage.directions,weapons:b.weaponLayout.budget,composition:b.weaponLayout.composition,issues:validateBlueprint(b),omissions:b.weaponLayout.omissions,functional:b.productionDesign.functionalPrefabIds,shots};}catch(e){return{ok:false,error:e.message};}
 },c);const name=`${c.shipyardId??'aegis'}-${c.length??300}-${c.family??result.family}-${c.seed}`;for(const{view,shot}of result.shots??[])await writeFile(`${out}/${name}-${view}.png`,png(shot.pixels));rows.push({...c,...result,shots:result.shots?.map(({view,shot:{pixels,...metadata}})=>({view,...metadata}))});console.log(JSON.stringify({...c,ok:result.ok,error:result.error,issues:result.issues,weapons:result.weapons?.byRegion}));}
 await writeFile(`${out}/report.json`,JSON.stringify({rows,errors},null,2));}finally{await browser.close();}
