import { PRIORITIES, ROLES } from "../blueprint/types";
import { SHIPYARDS } from "../shipyards/config";
export const PRIORITY_LABELS = {
  firepower: "Firepower",
  survivability: "Survivability",
  mobility: "Mobility",
  endurance: "Endurance",
  missile: "Missile capacity",
  sensor: "Sensor / EW",
};
const icons = ["▰", "◈", "▦", "⬡"];
export function layout() {
  return `
<header class="topbar"><div class="brand"><span class="brandmark">⟐</span><strong>PROCEDURAL<span>SHIPYARD</span></strong><span class="version">V1.8.5.3.1</span></div><div class="header-note">ORDER → BLUEPRINT → SHIP</div><span class="local-badge">LOCAL DESIGN LAB</span></header>
<main><aside class="order-panel"><div class="panel-heading"><span class="eyebrow">01 / COMMISSION</span><h1>Ship order<span>함선 발주서</span></h1></div>
<form id="order-form"><div class="order-fields"><section><div class="section-title"><h2>Shipyard</h2><span>설계 철학</span></div><div class="yard-grid">${SHIPYARDS.map((y, i) => `<button type="button" class="yard-card ${i === 0 ? "selected" : ""}" data-yard="${y.id}" aria-pressed="${i === 0}"><span class="yard-icon">${icons[i]}</span><span><b>${y.name.split(" ")[0]}</b><small>${y.doctrine}</small></span></button>`).join("")}</div><p id="doctrine" class="doctrine"></p></section>
<section><div class="section-title"><h2>Ship specification</h2><span>기본 조건</span></div><label class="field">Ship role<select id="role">${ROLES.map((r) => `<option ${r === "Cruiser" ? "selected" : ""}>${r}</option>`).join("")}</select></label><div class="length-label"><label for="length">Target length</label><output id="length-value">300 <span>m</span></output></div><input id="length" type="range" min="40" max="600" step="10" value="300"><div class="range-ends"><span>40 m</span><span>600 m</span></div><label class="field mass-field">Target mass class<select id="mass"><option>Light</option><option selected>Standard</option><option>Heavy</option><option>Superheavy</option></select></label></section>
<section><div class="section-title"><h2>Design priorities</h2><span>설계 우선순위</span></div><div class="priority-list">${PRIORITIES.map((k) => `<div class="priority"><label for="${k}">${PRIORITY_LABELS[k]}</label><output id="${k}-value"></output><input id="${k}" type="range" min="0" max="100" value="50"></div>`).join("")}</div></section>
</div><section class="seed-section"><div class="section-title"><h2>Design seed</h2><span>재현 가능한 설계</span></div><div class="seed-row"><span>#</span><input id="seed" aria-label="Design seed" type="number" min="0" max="4294967295" step="1" value="742091"><button type="button" id="random" title="Random Seed" aria-label="Random Seed">⤨</button></div><p class="seed-note">같은 주문서와 Seed는 같은 함선을 만듭니다.</p><button id="generate" class="primary" type="submit"><span>Generate new design</span><span>✧</span></button><button id="regenerate" class="secondary" type="button">Regenerate same seed</button><p id="order-status" role="status">발주서 준비 완료</p><div id="design-rejection"></div></section></form></aside>
<div class="workspace"><section class="viewer-panel"><div class="viewer-header"><div><span class="eyebrow">02 / DESIGN PREVIEW</span><h2 id="ship-name">Resolute</h2><div id="ship-subtitle" class="ship-subtitle"></div></div><span class="validated" id="validated">✓ BLUEPRINT VALID</span></div><div id="viewer"></div><div class="viewer-watermark">SHIPYARD<br><span>STRUCTURAL HIERARCHY & MESO / V1.8.5.3.1</span></div><div class="axis-label"><span class="axis-dot"></span> ISOMETRIC VIEW</div><div class="view-controls"><button id="iso" title="Isometric view">3D</button><button id="top" title="Top view">TOP</button><button id="rear" title="Rear view">AFT</button><button id="fit" title="Reset camera / Auto fit">⛶ <span>Fit</span></button></div><div class="viewer-footer"><div class="debug-tabs" role="group" aria-label="Debug View">${["Normal", "Hull Sections", "Hardpoints", "Engines", "Structure", "Architecture", "Structural Graph", "Integration", "Armor", "Equipment", "Hull Only", "Armor Coverage", "Armor Panels", "Panel Seams", "Secondary Armor", "Hardpoint Mounts", "Complete Ship", "Structural Armor Only", "Functional Exterior Only", "Hardpoint Layout Only", "Mount Size", "Symmetry Groups", "Firing Arc", "Surface Texture", "Decal Markings", "Meso Structures", "Without Meso", "Engine Root Zones", "Structural Junctions"].map((v, i) => `<button data-debug="${v}" class="${i === 0 ? "active" : ""}" aria-pressed="${i === 0}">${v}</button>`).join("")}</div><span class="orbit-hint">Drag to orbit · Scroll to zoom</span></div><label class="detail-control">Exterior detail <select id="detail-mode"><option>AUTO</option><option>OFF</option><option>LOW</option><option>HIGH</option></select></label><label class="detail-control">Surface finish <select id="surface-finish"><option>CLEAN</option><option>SERVICE</option><option>WEATHERED</option></select></label><div id="debug-legend" class="debug-legend" hidden></div><div id="viewer-error" class="viewer-error" hidden></div></section>
<section class="inspector"><div class="inspector-header"><div><span class="eyebrow">03 / BLUEPRINT</span><h2>Design manifest <span id="manifest-seed"></span></h2></div><div class="export-actions"><button id="import">↑ Import blueprint</button><input id="import-file" type="file" accept=".json,application/json" hidden><button id="reload">Reload stored</button><button id="inspect">View JSON</button><button id="export">↓ Export blueprint</button></div></div><div id="architecture-summary" class="architecture-summary"></div><div class="metrics" id="metrics"></div><div class="manifest-bottom"><span id="engine-pattern"></span><span id="generation-time"></span></div></section><footer class="bottom-note"><span>DESIGN RULES. NOT RANDOM NOISE.</span><span><a href="/qa.html">QA / Contact Sheets & Galleries ↗</a></span></footer></div></main>
<dialog id="json-dialog"><div class="dialog-header"><h2>ShipBlueprint JSON</h2><button id="close-json" aria-label="Close JSON">✕</button></div><p>현재 생성된 함선의 논리 설계 데이터</p><pre id="json-content"></pre><button id="copy-json">Copy JSON</button></dialog>`;
}
